services:
  music-renamer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: music-renamer
    restart: unless-stopped
    environment:
      MUSIC_INBOX: /inbox
      MUSIC_OUTDIR: /library      # dacă vrei in-place, pune MUSIC_OUTDIR=/inbox
      RENAME_TEMPLATE: "{artist} - {title}"   # șablon
    volumes:
      - /mnt/music-inbox:/inbox
      - /mnt/music-library:/library
    ports:
      - "8085:8080"